---
- hosts: db_servers
  become: True
  become_user: root
  gather_facts: false
  vars:
    cluster_name: test_cluster_pgcl
    postgres_version: "14"
 
  tasks:
    - name: manage postgresql      
      block:      
        
        # - name: init db
        #   shell:
        #     cmd: /usr/pgsql-14/bin/postgresql-14-setup initdb
        #   ignore_errors: yes
        
        - name: add role install pg_profile
          include_role:
            name: pg_install_pgprofile            
      become: True
      become_user: postgres
