---
all:
  hosts:
    host_mgr: ansible_ssh_host=192.168.2.1 ansible_ssh_user='vagrant' ansible_ssh_private_key_file='C:/workspace/centos1/.vagrant/machines/mgr/virtualbox/private_key'
  children:
    db_servers:
      hosts:
        host_db1: ansible_ssh_host=192.168.2.11 ansible_ssh_user='vagrant' ansible_ssh_private_key_file='C:/workspace/centos1/.vagrant/machines/mgr/virtualbox/private_key'
        host_db2: ansible_ssh_host=192.168.2.12 ansible_ssh_user='vagrant' ansible_ssh_private_key_file='C:/workspace/centos1/.vagrant/machines/mgr/virtualbox/private_key'
        host_db3: ansible_ssh_host=192.168.2.13 ansible_ssh_user='vagrant' ansible_ssh_private_key_file='C:/workspace/centos1/.vagrant/machines/mgr/virtualbox/private_key'
        
